name: Sync with smart-admin

on:
  schedule:
    - cron: '0 */2 * * *'  # 每天 UTC 时间的午夜执行同步

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 更新到 v3 版本
        with:
          ref: master  # 使用你的目标分支

      - name: Set up Git
        run: |
          git remote add upstream https://github.com/1024-lab/smart-admin.git
          git fetch upstream

      - name: Rebase onto upstream changes
        run: git rebase upstream/master
