name: Sync with smart-admin

on:
  schedule:
    - cron: '26 4 * * *'  # 每天午夜 4 点执行同步

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master  # 使用你的目标分支

      - name: Set up Git
        run: |
          git remote add upstream https://github.com/1024-lab/smart-admin.git
          git fetch upstream

      - name: Sync with upstream
        run: |
          git reset --hard upstream/master
